In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np 
# 1D array
arr1 = np.array([1,2,3,5,6])
print(arr1)
print(arr1.shape) 

[1 2 3 5 6]
(5,)


In [11]:
# 2D array
arr2 = np.array([[1,2,3,5,6],[1,324,34,534,634]])
arr2.reshape(2,5)

array([[  1,   2,   3,   5,   6],
       [  1, 324,  34, 534, 634]])

In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size (number of elements):",arr.size)
print("Data type:",arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int32
Item size (in bytes): 4


In [18]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

# Element Wise Addition
print("Addition: ",arr1+arr2)

# Element wise Subtraction
print("Subtraction: ",arr1-arr2)

# Element Wise Multiplication
print("Multiplication: ",arr1*arr2)

# Element Wise Division
print("Division: ",arr1/arr2)


Addition:  [ 7  9 11 13 15]
Subtraction:  [-5 -5 -5 -5 -5]
Multiplication:  [ 6 14 24 36 50]
Division:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [20]:
## Universal Function
arr = np.array([2,5,5,6,7])

## Square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 2.23606798 2.23606798 2.44948974 2.64575131]
[   7.3890561   148.4131591   148.4131591   403.42879349 1096.63315843]
[ 0.90929743 -0.95892427 -0.95892427 -0.2794155   0.6569866 ]
[0.69314718 1.60943791 1.60943791 1.79175947 1.94591015]


In [26]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [29]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [31]:
# Normalization
data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean)/std_dev
print("Normalized data:",normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [33]:
mean = np.mean(data)
print("Mean: ",mean)

# Media 
median = np.median(data)
print("Median:",median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:",std_dev)


# Variance
variance = np.var(data)
print("Variance:",variance)

Mean:  3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


In [34]:
# Logical Operation
data = np.array([1,2,3,5,6,7,8,10])

data[(data >=5)&(data <=8)]

array([5, 6, 7, 8])