In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [10]:
# Assignment 1: Array Creation and Manipulation
arr = np.random.randint(1,20,(5,5))
arr[0:,2] = 1
arr


array([[ 3,  3,  1,  2, 11],
       [ 3,  2,  1,  4, 16],
       [ 3, 13,  1,  2,  6],
       [10, 15,  1,  9, 11],
       [ 3,  5,  1, 18,  1]])

In [11]:
arr = np.random.randint(1,16,(4,4))

np.fill_diagonal(arr,0)
arr

array([[ 0,  8, 12,  6],
       [ 7,  0,  3, 12],
       [11, 10,  0,  3],
       [15,  7, 13,  0]])

In [13]:
# Assignment 2: Array Indexing and Slicing
arr = np.random.randint(1,36,(6,6))
arr[2:6,1:5]

array([[15, 10, 18, 32],
       [35, 15,  7, 17],
       [ 2, 31,  3, 31],
       [26, 11, 12, 13]])

In [21]:
arr = np.random.randint(1,50,(5,5))
print(arr)
row,col = arr.shape
result =  np.concatenate((arr[0, :], arr[-1, :], arr[1:-1, 0], arr[1:-1, -1]))
print(result)

[[24 13  2 31 37]
 [12  9 49 34  9]
 [18 15 25 12 47]
 [37 31  9 14 37]
 [28 48  7 33 10]]
[24 13  2 31 37 28 48  7 33 10 12 18 37  9 47 37]


In [24]:
# Assignment 3: Array Operations
arr1 = np.random.randint(1,30,(3,4))
arr2 = np.random.randint(1,30,(3,4))

add = arr1 + arr2
sub = arr1 - arr2
mul = arr1 * arr2
div = arr1 / arr2
print(add)
print(sub)
print(mul)
print(div)

[[36 32 30 14]
 [38 14 45 14]
 [33 22 28 35]]
[[ 22  10 -16  -8]
 [ 18  10  -9  -4]
 [ 23  -8  24 -17]]
[[203 231 161  33]
 [280  24 486  45]
 [140 105  52 234]]
[[ 4.14285714  1.90909091  0.30434783  0.27272727]
 [ 2.8         6.          0.66666667  0.55555556]
 [ 5.6         0.46666667 13.          0.34615385]]


In [26]:
arr = np.arange(1,17).reshape((4,4))
row_sum = np.sum(arr,axis=1)
col_sum = np.sum(arr,axis=0)
result = row_sum + col_sum

print(f"Row wise addition: {row_sum}")
print(f"Col wise addition: {col_sum}")


Row wise addition: [10 26 42 58]
Col wise addition: [28 32 36 40]


In [29]:
# Assignment 4: Statistical Operations
arr = np.random.randint(1,21,(5,5))
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
var = np.var(arr)

print(f"Mean: {mean}\nMedia: {median}\nStandard Deviation: {std_dev}\nVariance: {var}")

Mean: 11.44
Media: 12.0
Standard Deviation: 6.145437331874763
Variance: 37.7664


In [30]:
arr = np.random.randint(1,9,(3,3))

mean = np.mean(arr)
std_dev = np.std(arr)

normalized = (arr - mean)/std_dev
print(normalized)

[[ 0.32496684  0.74278135  1.16059586]
 [-0.92847669 -1.3462912   1.57841037]
 [ 0.32496684 -0.92847669 -0.92847669]]


In [31]:
# Assignment 5: Broadcasting
arr = np.random.randint(1,100,(3,3))
row_array = np.random.randint(1,11,(3,))

print(f"Original Array: {arr}")
print(f"Row Array: {row_array}")

result = arr + row_array
print(f"Resultant Array: {result}")

Original Array: [[81 48 87]
 [54 58 63]
 [ 1 84 63]]
Row Array: [2 2 8]
Resultant Array: [[83 50 95]
 [56 60 71]
 [ 3 86 71]]


In [34]:
arr = np.random.randint(1,50,(4,4))
oned_array = np.random.randint(1,11,(4,))

result = arr - oned_array
print(f"Result Array: {result}")

Result Array: [[14  5 30  7]
 [ 6 41 29 37]
 [17 27 13 44]
 [ 3 17 20 16]]


In [35]:
# Assignment 6: Linear Algebra
arr = np.random.randint(1,11,(3,3))
determinant = np.linalg.det(arr)

inverse = np.linalg.inv(arr)

eigen_value = np.linalg.eigvals(arr)

print(f"Determinant: {determinant}\nInverse: {inverse}\nEigen Value: {eigen_value}")

Determinant: 167.99999999999997
Inverse: [[ 0.19047619  0.04761905 -0.0952381 ]
 [-0.20238095  0.26190476 -0.02380952]
 [-0.0297619  -0.22619048  0.20238095]]
Eigen Value: [18.56133178+0.j         2.71933411+1.2869719j  2.71933411-1.2869719j]


In [36]:
arr1 = np.random.randint(1,11,(2,3))
arr2 = np.random.randint(1,11,(3,2))

result = np.matmul(arr1,arr2)
print(f"Result: {result}")

Result: [[38 40]
 [45 96]]


In [39]:
# Assignment 7: Advanced Array Manipulation
arr = np.arange(1,10).reshape((3,3))
reshaped_arr1 = arr.reshape((1,9))
reshaped_arr2 = arr.reshape((9,1))

In [42]:
arr = np.arange(1,26).reshape((5,5))
flattened_array = np.ndarray.flatten(arr)
print(flattened_array)
reshaped = flattened_array.reshape((5,5))
print(reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [43]:
# Assignment 8: Fancy Indexing and Boolean Indexing
arr = np.arange(1,26).reshape((5,5))
corners = arr[[0, 0, -1, -1], [0, -1, 0, -1]]
print(f"Corner Element: {corners}")

Corner Element: [ 1  5 21 25]


In [46]:
arr = np.arange(1,17).reshape((4,4))
arr[arr > 10] = 10
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 10]
 [10 10 10 10]]


In [48]:
# Assignment 9: Structured Arrays
data_type = [('name','U10'),('age','i4'),('weight','f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original Array: ")
print(data)
# sort the array by age
sorted_data = np.sort(data,order='age')
print(sorted_data)

Original Array: 
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [49]:
data_type = [('x','i4'),('y','i4')]
data = np.array([(1,2),(3,4),(5,6)],dtype=data_type)
print("Original Array")
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)

print(distances)


Original Array
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [51]:
# Assignment 10: Masked Arrays
array = np.random.randint(1, 21, size=(4, 4))
masked_array = np.ma.masked_greater(array, 10)
print(array)
print(masked_array)

[[ 2 12 17 14]
 [10 18 18  9]
 [12  9 13 11]
 [17 16  1  9]]
[[2 -- -- --]
 [10 -- -- 9]
 [-- 9 -- --]
 [-- -- 1 9]]


In [54]:
array = np.random.randint(1,11,(3,3))
masked_array = np.ma.masked_array(array, mask=np.eye(3, dtype=bool))
print(masked_array)
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print(masked_array)

[[-- 6 4]
 [2 -- 5]
 [8 3 --]]
[[4 6 4]
 [2 4 5]
 [8 3 4]]
